## Pandas_ calculation
- 연산 함수
    - add(), sub(), mul(), div()
    - 연산자를 사용한 연산도 가능
    - 정렬(sort), 요약 및 통계 연산, 유일 값, 값 세기

In [2]:
import numpy as np
import pandas as pd

In [5]:
df1 = pd.DataFrame(np.arange(12.).reshape((3, 4)), columns=list('abcd'))
df2 = pd.DataFrame(np.arange(20.).reshape((4, 5)), columns=list('abcde'))

print(df1)
print(df2)

     a    b     c     d
0  0.0  1.0   2.0   3.0
1  4.0  5.0   6.0   7.0
2  8.0  9.0  10.0  11.0
      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   6.0   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [8]:
df1.add(df2, fill_value=0)

a     b     c     d     e
0   0.0   2.0   4.0   6.0   4.0
1   9.0   5.0  13.0  15.0   9.0
2  18.0  20.0  22.0  24.0  14.0
3  15.0  16.0  17.0  18.0  19.0

In [9]:
df1 + df2

a     b     c     d   e
0   0.0   2.0   4.0   6.0 NaN
1   9.0   NaN  13.0  15.0 NaN
2  18.0  20.0  22.0  24.0 NaN
3   NaN   NaN   NaN   NaN NaN

In [10]:
df1.mul(df2, fill_value=0)

a     b      c      d    e
0   0.0   1.0    4.0    9.0  0.0
1  20.0   0.0   42.0   56.0  0.0
2  80.0  99.0  120.0  143.0  0.0
3   0.0   0.0    0.0    0.0  0.0

In [6]:
df2.loc[1, 'b'] = np.nan # 해당 위치 값을 NaN로 저장
print(df2)

      a     b     c     d     e
0   0.0   1.0   2.0   3.0   4.0
1   5.0   NaN   7.0   8.0   9.0
2  10.0  11.0  12.0  13.0  14.0
3  15.0  16.0  17.0  18.0  19.0


In [7]:
# reindex() : index 재설정하기
df1.reindex(columns=df2.columns, fill_value=0)

a    b     c     d  e
0  0.0  1.0   2.0   3.0  0
1  4.0  5.0   6.0   7.0  0
2  8.0  9.0  10.0  11.0  0

In [11]:
arr = np.arange(12.).reshape((3,4))
arr

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.]])

In [12]:
print(arr[0], '\n')
print(arr - arr[0])

[0. 1. 2. 3.] 

[[0. 0. 0. 0.]
 [4. 4. 4. 4.]
 [8. 8. 8. 8.]]


In [13]:
frame = pd.DataFrame(np.arange(12.).reshape((4,3)),
                     columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
series = frame.iloc[0]
print(frame, '\n')
print(series)

          b     d     e
Utah    0.0   1.0   2.0
Ohio    3.0   4.0   5.0
Texas   6.0   7.0   8.0
Oregon  9.0  10.0  11.0 

b    0.0
d    1.0
e    2.0
Name: Utah, dtype: float64


In [14]:
frame - series

b    d    e
Utah    0.0  0.0  0.0
Ohio    3.0  3.0  3.0
Texas   6.0  6.0  6.0
Oregon  9.0  9.0  9.0

In [15]:
series2 = pd.Series(range(3), index=['b', 'e', 'f'])
print(series2)

b    0
e    1
f    2
dtype: int64


In [16]:
frame + series2

b   d     e   f
Utah    0.0 NaN   3.0 NaN
Ohio    3.0 NaN   6.0 NaN
Texas   6.0 NaN   9.0 NaN
Oregon  9.0 NaN  12.0 NaN

In [18]:
series4 = frame.loc["Ohio"]
series4

b    3.0
d    4.0
e    5.0
Name: Ohio, dtype: float64

In [19]:
frame.sub(series4, axis='columns')

b    d    e
Utah   -3.0 -3.0 -3.0
Ohio    0.0  0.0  0.0
Texas   3.0  3.0  3.0
Oregon  6.0  6.0  6.0

In [20]:
series3 = frame['d']
series3

Utah       1.0
Ohio       4.0
Texas      7.0
Oregon    10.0
Name: d, dtype: float64

In [21]:
frame.sub(series3, axis='index')

b    d    e
Utah   -1.0  0.0  1.0
Ohio   -1.0  0.0  1.0
Texas  -1.0  0.0  1.0
Oregon -1.0  0.0  1.0

In [24]:
frame = pd.DataFrame(np.random.randn(4,3), columns=list('bde'),
                     index=['Utah', 'Ohio', 'Texas', 'Oregon'])
frame

b         d         e
Utah    1.462020 -0.265534 -0.153806
Ohio   -0.522992 -1.281155  1.142057
Texas   1.562755  0.771013 -0.894291
Oregon -0.571733  2.343979  1.212344

In [25]:
np.abs(frame)

b         d         e
Utah    1.462020  0.265534  0.153806
Ohio    0.522992  1.281155  1.142057
Texas   1.562755  0.771013  0.894291
Oregon  0.571733  2.343979  1.212344

In [26]:
frame.sum()

b    1.930050
d    1.568301
e    1.306305
dtype: float64

In [27]:
frame.sum(axis=0)

b    1.930050
d    1.568301
e    1.306305
dtype: float64

In [28]:
frame.sum(axis=1)

Utah      1.042680
Ohio     -0.662090
Texas     1.439476
Oregon    2.984590
dtype: float64

In [29]:
frame.apply(np.sum, axis=1)

Utah      1.042680
Ohio     -0.662090
Texas     1.439476
Oregon    2.984590
dtype: float64

In [30]:
frame.max()

b    1.562755
d    2.343979
e    1.212344
dtype: float64

In [31]:
frame.max(axis=0)

b    1.562755
d    2.343979
e    1.212344
dtype: float64

In [32]:
frame.apply(np.max, axis=0)

b    1.562755
d    2.343979
e    1.212344
dtype: float64

In [33]:
frame.apply(np.max)

b    1.562755
d    2.343979
e    1.212344
dtype: float64

- `apply()` : 특정 행 또는 열, 전체 데이터 프레임에 함수, 연산을 적용할 때 사용
    - 단일 연산인 경우 전체에 적용된다.
    - numpy의 min, max, average와 같이 집계되는 경우 축을 지정한다.

In [34]:
import math

In [35]:
df1 = pd.DataFrame({'국어': [51, 65, 88], '수학': [80, 95, 85]},
                   index=['홍길동', '이순신', '김유신'])
df1

국어  수학
홍길동  51  80
이순신  65  95
김유신  88  85

In [36]:
df1.apply(np.sqrt)

국어        수학
홍길동  7.141428  8.944272
이순신  8.062258  9.746794
김유신  9.380832  9.219544

In [39]:
df1.apply(np.sqrt, axis=0)

국어        수학
홍길동  7.141428  8.944272
이순신  8.062258  9.746794
김유신  9.380832  9.219544

In [40]:
df1.apply(np.sum, axis=0)

국어    204
수학    260
dtype: int64

In [41]:
df1.apply(sum)

국어    204
수학    260
dtype: int64

In [42]:
df1.sum(axis=1)

홍길동    131
이순신    160
김유신    173
dtype: int64

In [43]:
df1.apply(np.sum, axis=1)

홍길동    131
이순신    160
김유신    173
dtype: int64

In [44]:
df1.max()

국어    88
수학    95
dtype: int64

In [45]:
df1.max(axis=0)

국어    88
수학    95
dtype: int64

In [46]:
df1.apply(np.max, axis=0)

국어    88
수학    95
dtype: int64

In [47]:
df1.apply(np.max)

국어    88
수학    95
dtype: int64

In [48]:
f = lambda x: x.max() - x.min()
df1.apply(f)

국어    37
수학    15
dtype: int64

In [49]:
df1.apply(f, axis='columns')

홍길동    29
이순신    30
김유신     3
dtype: int64

In [50]:
pd.DataFrame([df1.min(), df1.max()], index=['min', 'max'])

국어  수학
min  51  80
max  88  95

In [51]:
pd.Series([df1.min(), df1.max()], index=['min', 'max'])

min    국어    51
수학    80
dtype: int64
max    국어    88
수학    95
dtype: int64
dtype: object

In [52]:
def f(x):
    return pd.Series([x.min(), x.max()], index=['min', 'max'])
df1.apply(f)

국어  수학
min  51  80
max  88  95

In [3]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                   [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [4]:
df.sum()

one    9.25
two   -5.80
dtype: float64

In [5]:
df.apply(np.sum, axis=0)

one    9.25
two   -5.80
dtype: float64

In [6]:
df.sum(axis='columns')

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [7]:
df.apply(np.sum, axis=1)

a    1.40
b    2.60
c    0.00
d   -0.55
dtype: float64

In [8]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [9]:
df.mean(axis='columns', skipna=False)

a      NaN
b    1.300
c      NaN
d   -0.275
dtype: float64

In [10]:
df.mean(axis='columns', skipna=True)

a    1.400
b    1.300
c      NaN
d   -0.275
dtype: float64

#### 정렬(sort) : `DataFrame.sort_index()`
축을 따라 개체를 정렬

In [11]:
obj = pd.Series(range(4), index=['d', 'a', 'b', 'c'])
obj

d    0
a    1
b    2
c    3
dtype: int64

In [12]:
frame = pd.DataFrame(np.arange(8).reshape((2, 4)),
                     index=['three', 'one'],
                     columns=['d', 'a', 'b', 'c'])
frame

d  a  b  c
three  0  1  2  3
one    4  5  6  7

In [13]:
frame.sort_index()

d  a  b  c
one    4  5  6  7
three  0  1  2  3

In [14]:
frame.sort_index(axis=1)

a  b  c  d
three  1  2  3  0
one    5  6  7  4

- 데이터의 크기 순으로 정렬

In [15]:
obj = pd.Series([4, np.nan, 7, np.nan, -3, 2])
obj.sort_values()

4   -3.0
5    2.0
0    4.0
2    7.0
1    NaN
3    NaN
dtype: float64

In [16]:
frame = pd.DataFrame({'b': [4, 7, -3, 2], 'a': [0, 1, 0, 1]})
frame

b  a
0  4  0
1  7  1
2 -3  0
3  2  1

In [17]:
frame.sort_values(by='b')

b  a
2 -3  0
3  2  1
0  4  0
1  7  1

In [18]:
frame.sort_values(by=['a', 'b'])

b  a
2 -3  0
0  4  0
3  2  1
1  7  1

#### `DataFrame.value_counts()`
- 어떤 컬럼의 unique value들의 개수를 구한다.

In [19]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [20]:
obj.describe()

count     9
unique    4
top       c
freq      3
dtype: object

In [21]:
#빈도가 큰순으로 표시
obj.value_counts()

c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [22]:
# 빈도가 큰순으로 표시
pd.value_counts(obj.values, sort=True)

/var/folders/g6/3qldr4jd21lbltbbdswtbqkm0000gn/T/ipykernel_8041/2322870717.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=True)


c    3
a    3
b    2
d    1
Name: count, dtype: int64

In [23]:
# 값 순서대로 빈도 표시
pd.value_counts(obj.values, sort=False)

/var/folders/g6/3qldr4jd21lbltbbdswtbqkm0000gn/T/ipykernel_8041/316527124.py:2: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  pd.value_counts(obj.values, sort=False)


c    3
a    3
d    1
b    2
Name: count, dtype: int64

#### `DataFrame.unique()`
- 고유한 값을 반환

In [24]:
obj = pd.Series(['c', 'a', 'd', 'a', 'a', 'b', 'b', 'c', 'c'])
obj

0    c
1    a
2    d
3    a
4    a
5    b
6    b
7    c
8    c
dtype: object

In [25]:
obj.describe()

count     9
unique    4
top       c
freq      3
dtype: object

In [26]:
uniques = obj.unique()
uniques

array(['c', 'a', 'd', 'b'], dtype=object)

#### `fillna()`: 결측 데이터를 대체하는 함수

In [27]:
data = pd.DataFrame({'Qu1': [1, 3, 4, 3, 4],
                    'Qu2': [2, 3, 1, 2, 3],
                    'Qu3': [1, 5, 2, 4, 4]})
data

Qu1  Qu2  Qu3
0    1    2    1
1    3    3    5
2    4    1    2
3    3    2    4
4    4    3    4

In [28]:
result = data.value_counts()
result

Qu1  Qu2  Qu3
1    2    1      1
3    2    4      1
     3    5      1
4    1    2      1
     3    4      1
Name: count, dtype: int64

In [29]:
result = data.apply(pd.value_counts)  #각 열의 빈도수를 계산
result

/var/folders/g6/3qldr4jd21lbltbbdswtbqkm0000gn/T/ipykernel_8041/664432881.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts)  #각 열의 빈도수를 계산


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  NaN  2.0  1.0
3  2.0  2.0  NaN
4  2.0  NaN  2.0
5  NaN  NaN  1.0

In [31]:
result = data.apply(pd.value_counts).fillna(0)
result

/var/folders/g6/3qldr4jd21lbltbbdswtbqkm0000gn/T/ipykernel_8041/1382616601.py:1: FutureWarning: pandas.value_counts is deprecated and will be removed in a future version. Use pd.Series(obj).value_counts() instead.
  result = data.apply(pd.value_counts).fillna(0)


Qu1  Qu2  Qu3
1  1.0  1.0  1.0
2  0.0  2.0  1.0
3  2.0  2.0  0.0
4  2.0  0.0  2.0
5  0.0  0.0  1.0

#### 요약 및 통계 연산

In [32]:
df = pd.DataFrame([[1.4, np.nan], [7.1, -4.5],
                  [np.nan, np.nan], [0.75, -1.3]],
                  index=['a', 'b', 'c', 'd'],
                  columns=['one', 'two'])
df

one  two
a  1.40  NaN
b  7.10 -4.5
c   NaN  NaN
d  0.75 -1.3

In [33]:
# 누적 합
df.cumsum()

one  two
a  1.40  NaN
b  8.50 -4.5
c   NaN  NaN
d  9.25 -5.8

In [34]:
df.describe()

one       two
count  3.000000  2.000000
mean   3.083333 -2.900000
std    3.493685  2.262742
min    0.750000 -4.500000
25%    1.075000 -3.700000
50%    1.400000 -2.900000
75%    4.250000 -2.100000
max    7.100000 -1.300000

In [35]:
obj = pd.Series(['a', 'a', 'b', 'c'] * 4)
obj

0     a
1     a
2     b
3     c
4     a
5     a
6     b
7     c
8     a
9     a
10    b
11    c
12    a
13    a
14    b
15    c
dtype: object

In [36]:
# 산술 데이터가 아닌 기술 통계 정보
obj.describe()

count     16
unique     3
top        a
freq       8
dtype: object