## Python list와 Numpy array
- `python list` : 단일 리스트 내에 다양한 종류의 데이터 포함
    - 리스트는 다양한 자료형의 데이터를 여러 개 저장 가능, 데이터를 변경하거나 추가, 제거할 수 있다.
- `numpy array`
    - **수학 및 과학을 위한 파이썬 패키지**
    - 넘파이 배열은 모든 요소가 같은 종류의 데이터로 구성
    - 넘파이 배열은 파이썬 리스트보다 빠르고 간결하며 훨씬 더 적은 메모리를 사용
        - 대용량 데이터 배열을 효율적으로 다룰 수 있다
        - 넘파이 연산은 파이썬 반복문을 사용하지 않고 전체 배열에 대한 복잡한 계산 수행
        - 판다스, opencv 등 유명한 라이브러리가 넘파이 기반
    - 배열의 내용을 한번에 디스크에 저장하고, 다시 불러오는 기능을 제공
    - C, C++ 로 작성한 코드와 연결 가능

### Numpy ndarray
- ndarray 클래스 : 다차원 배열 객체
    - N차원의 배열 객체
        - 대규모 데이터 집합을 담을 수 있는 빠르고 유연한 자료 구조
        - C언어에 기반한 배열 구조이므로 메모리를 적게 차지하고 속도가 빠르다.
        - 배열과 배열 간에 수학적인 연산을 적용할 수 있다
        - 고급 연산자와 풍부한 함수들을 제공
    - 1차원 배열 : vectorm 2차원 배열 : matrix, 3차원 배열 : tensor
    - 배열 내부의 각 요소 : index라고 불리는 정수들로 참조
    - 넘파이에서 차원은 **축(axis)** 이라고 부른다

- 다차원 배열의 속성
    - 배열은 고정 크기의 동일한 유형 및 크기의 항목으로 구성
    - 배열의 차원 및 항목 수는 배열의 모양에 의해 정의
        - 배열의 모양(shape) : 각 차원의 크기를 지정하는 음이 아닌 정수의 튜플로 나타낸다.

    | 속성 | 설명 |
    |:---:|:---:|
    | ndim | 배열의 축(차원)의 개수 |
    | shape | 배열의 차원을 나타내는 정수의 튜플 |
    | size | 배열의 요소의 총 개수 |
    | dtype | 배열 요소의 데이터 유형 |
    | itemsize | 배열의 각 요소의 크기(바이트) |
    | data | 배열의 실제 요소를 포함하는 버퍼 |
    | strides | 배열의 각 차원을 따라 이동하기 위해 필요한 바이트 수 |
  
### Numpy 배열 생성
- 넘파이는 주로 1차원, 2차원, 3차원 등의 배열을 처리하기 위한 용도로 만들어짐

    | numpy 함수 | 설명 |
    |:---:|:---:|
    | np.array | 파이썬 리스트를 넘파이 배열로 변환, 변환 시 데이터 형 지정 가능 |
    | np.arange | range 함수와 유사, 배열을 생성 |
    | np.ones, np.zeros | 1 또는 0으로 채워진 배열 생성 |
    | np.empty | 초기화되지 않은 배열 생성 (쓰레기값이 들어있다.) |
    | np.full | 지정된 상수로 배열 생성 |
    | np.identity | 단위 행렬 생성 |

In [2]:
import numpy as np

In [6]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)

[[1 2 3]
 [4 5 6]]


In [7]:
arr2 = np.array([[1,2,3], [4,5,6]])
print(arr2)             #배열 출력
print(arr2.shape)       #행렬의 크기
print(arr2.ndim)        #배열 축 혹은 차원의 개수를 반환
arr2.dtype              #배열 요소의 데이터 타입을 반환

[[1 2 3]
 [4 5 6]]
(2, 3)
2


dtype('int64')

In [10]:
a = np.array([1,2,3])                                                   #1차원 배열
b = np.array([[1,2,3], [4,5,6], [7,8,9]])                               #2차원 배열
c = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]], [[9, 10], [11, 12]]])         #3차원 배열
print(a, '\n')                #1차원 배열 출력    
print(b, '\n')                #2차원 배열 출력
print(c, '\n')                #3차원 배열 출력
print(a[0], b[0][1], c[0][1][1])   #0번째 요소 출력, 0번째 요소의 1번째 요소 출력, 0번째 요소의 1번째 요소의 1번째 요소 출력

[1 2 3] 

[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]] 

1 2 4


In [11]:
print(a.shape, a.ndim, a.size)     
print(b.shape, b.ndim, b.size)
print(c.shape, c.ndim, c.size)                                    #1차원 배열의 크기, 차원, 데이터 타입

(3,) 1 3
(3, 3) 2 9
(3, 2, 2) 3 12


### Numpy 데이터 자료형
- 파이썬 리스트와 달리 넘파이 배열은 데이터 형식을 지정
- dtype : 넘파이 배열 데이터의 자료형 확인 및 지정
- astype() : 이미 지정된 데이터 자료형을 변경

    | 데이터 타입 | 설명 |
    |:---:|:---:|
    | int8, int16, int32, int64 | 부호가 있는 정수 |
    | uint8, uint16, uint32, uint64 | 부호가 없는 정수 |
    | float16, float32, float64, float128 | 부동 소수점 수 |
    | bool | 불리언 |
    | string_ | 영문 기준 문자열 |
    | unicode_ | 한글 등, 기준 문자열 |

In [12]:
# 데이터 자료형 지정 방법 1
a = np.array([1, 2, 3, 4], dtype = np.int32)        # 정수형 배열
print(a)
a.dtype

[1 2 3 4]


dtype('int32')

In [13]:
# 데이터 자료형 지정 방법 2
a = np.array([1, 2, 3, 4], dtype = 'int32')        #정수형 배열
print(a)
a.dtype

[1 2 3 4]


dtype('int32')

In [14]:
a = np.array([1, 2, 3, 4], dtype = 'int32')
print(a)
print(a.dtype)
print(a.astype(float))
print(a.dtype)

b = a.astype(float)
print(b.dtype)

[1 2 3 4]
int32
[1. 2. 3. 4.]
int32
float64


- 파이썬에는 배열 데이터 구조가 없으며 리스트를 이용해 유사 배열 (array-like)을 만든다.
- 넘파이 배열 : 유사 배열인 리스트 데이터를 입력해 처리한 결과를 말한다 -> ndarray 객체

In [18]:
# 리스트로 넘파이 배열(1차원) 생성
import numpy as np
arr1 = np.array([0, 2, 5.5, 7])
print(arr1)
print(arr1.dtype)

[0.  2.  5.5 7. ]
float64


In [19]:
# 리스트로 넘파이 배열(1차원) 생성
list1 = [0, 2, 5.5, 7]
arr1 = np.array(list1)
print(arr1)

[0.  2.  5.5 7. ]


In [20]:
a = np.array([1, 2, 3, 4])
print(a)
print(type(a))
print(a.dtype)

b = np.array([1.2, 3, 5.1])
print(b)
print(type(b))
print(b.dtype)

[1 2 3 4]
<class 'numpy.ndarray'>
int64
[1.2 3.  5.1]
<class 'numpy.ndarray'>
float64


### 배열 생성 함수 (초기화)
- `np.zeros()`: 배열의 shape를 인자로 넘기면, 모든 요소가 0인 배열을 생성

In [21]:
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [22]:
type(arr)

numpy.ndarray

In [23]:
arr.shape

(5,)

In [25]:
arr.dtype

dtype('float64')

In [26]:
arr = np.zeros(shape=(6, 2))
arr

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [27]:
arr1 = np.zeros((6, 2))
arr1

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.],
       [0., 0.]])

In [28]:
arr1.size

12

- `np.ones()`: 배열의 shape를 인자로 넘기면, 모든 요소가 1인 배열을 생성
- `np.eye()`, `np.identity()`: 단위 행렬 생성

In [30]:
np.ones(5)

array([1., 1., 1., 1., 1.])

In [31]:
np.ones((5,), dtype=int)

array([1, 1, 1, 1, 1])

In [32]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [33]:
np.eye(3)       # 3x3 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [34]:
np.eye(3, dtype=int)        # 3x3 정수형 단위행렬

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

In [35]:
np.identity(3)          # 3x3 단위행렬

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
#k 가 1이므로 대각선 기준으로 하여 1단계 위로 1이 배치
np.eye(3, k=1)

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [37]:
# k가 1이므로 대각선 기준으로 하여 1단계 아래로 1이 배치
np.eye(3, k=-1)

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

- `np.empty()`: 배열의 shape을 인자로 넘기면, 배열은 할당된 메모리 주소의 기존 값을 취한다.
    - 주어진 shape와 타입의 배열을 생성하지만 값을 초기화하지 않는다.
    - 해당 메모리 영역에 어떤 데이터가 남아있었던지 상관없이 그대로 영역의 주소만 알려줄 뿐이다.
    - empty함수를 실행할때마다 값이 다르다.

In [49]:
np.empty((2, 2))

array([[0., 0.],
       [0., 0.]])

In [50]:
np.empty((2, 2), dtype=int)     # 2x2 정수형 배열 생성

array([[0, 0],
       [0, 0]])

In [51]:
arr = np.empty((2,2), dtype=int)
arr

array([[0, 0],
       [0, 0]])

- `np.linspace()`: 시작과 끝의 값을 지정하고 그 사이의 값을 균등하게 배분

In [52]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

In [53]:
np.linspace(1,10,5)     # 1부터 10까지 5개로 나눈 배열 생성

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [55]:
np.linspace(1,10, num=5)

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [56]:
np.linspace(2.0, 3.0, num=5)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

In [57]:
# endpoint : 지정하지 않으면 True
np.linspace(2.0, 3.0, num=5, endpoint=False)

array([2. , 2.2, 2.4, 2.6, 2.8])

In [58]:
np.linspace(2.0, 3.0, num=5, endpoint=True)

array([2.  , 2.25, 2.5 , 2.75, 3.  ])

- `np.arange()`: 시작, 끝, 단계를 지정하여 배열 생성

In [59]:
arr = np.arange(5)
arr

array([0, 1, 2, 3, 4])

In [60]:
np.arange(1, 5)

array([1, 2, 3, 4])

In [61]:
np.arange(1, 10, 2)

array([1, 3, 5, 7, 9])

In [62]:
np.arange(5.)

array([0., 1., 2., 3., 4.])

In [63]:
np.arange(1., 5.)

array([1., 2., 3., 4.])

In [64]:
np.arange(1, 10.5, 2.5)

array([1. , 3.5, 6. , 8.5])

### 난수 기반 배열 생성 함수 : random 서브 모듈
- random 서브 모듈에 포함된 중요한 난수 관련 함수
    
    | 함수 | 설명 |
    |:---:|:---:|
    | rand() | 균등 분포에서 난수 표본 추출 |
    | randn() | 표준 정규 분포에서 난수 표본 추출 |
    | randint() | 주어진 최소, 최대 범위에서 임의의 난수 추출 |
    | normal() | 정규 분포에서 난수 추출 |
    | uniform() | 균등(0, 1) 분포에서 난수 추출 |
    | shuffle() | 주어진 리스트나 다차원 배열의 순서를 임의로 뒤섞음 |


In [65]:
np.random.seed(100) # 같은 시드를 설정하면 동일한 난수가 발생
np.random.rand(5)

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [66]:
np.random.rand(5, 3)

array([[0.12156912, 0.67074908, 0.82585276],
       [0.13670659, 0.57509333, 0.89132195],
       [0.20920212, 0.18532822, 0.10837689],
       [0.21969749, 0.97862378, 0.81168315],
       [0.17194101, 0.81622475, 0.27407375]])

In [67]:
np.random.randint(1, 7, size=10)

array([4, 4, 4, 2, 2, 6, 4, 1, 3, 2])

In [68]:
np.random.randint(1, 11, size=(4, 7))

array([[10,  4,  3,  6,  9,  2,  1],
       [ 8,  7,  3,  1,  9,  3,  6],
       [ 2,  9,  2,  6,  5,  3,  9],
       [ 4,  6,  1, 10,  4,  7,  4]])

In [69]:
# 12명의 키를 난수로 생성, 평균은 175cm, 표준편차는 10인 정규분포

np.random.seed(100) # 같은 시드를 설정하면 동일한 난수가 발생
m = 175
sigma = 10
heights = m+sigma*np.random.randn(12)
heights

array([157.50234527, 178.42680403, 186.53035803, 172.47563963,
       184.81320787, 180.14218841, 177.21179669, 164.29956669,
       173.10504169, 177.55001444, 170.41973014, 179.35163488])

In [70]:
# 평균값이 175, 표준편차가 10인 정규 분포 함수 생성
np.random.seed(100)
nums = np.random.normal(loc=175, scale=10, size=(3, 4)).round(2)
nums

array([[157.5 , 178.43, 186.53, 172.48],
       [184.81, 180.14, 177.21, 164.3 ],
       [173.11, 177.55, 170.42, 179.35]])

### 배열 요소 추가 : np.append()
- 배열 arr의 끝에 values를 추가한 결과를 반환, 배열 arr 자체는 변경되지 않음
- 축을 지정하지 않으면 배열 arr과 values는 모두 평탄하게 바뀐 후 (축이 없어짐), values를 추가하고 그 결과를 반환한다.

In [71]:
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [72]:
arr = np.array([1, 2, 3])
arr1 = np.append(arr, 4)
print(arr)
print(arr1)

[1 2 3]
[1 2 3 4]


In [73]:
arr = np.array([1, 2, 3])
arr1 = np.array([[4, 5], [6, 7]])
print(arr)
print(arr1)

[1 2 3]
[[4 5]
 [6 7]]


In [74]:
arr2 = np.append(arr, arr1)
print(arr2)

[1 2 3 4 5 6 7]


In [76]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [77]:
arr1.shape

(2, 3)

In [78]:
np.append(arr1, [[7, 8, 9]], axis=0)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [79]:
np.append(arr1, ([7], [8]), axis=1)

array([[1, 2, 3, 7],
       [4, 5, 6, 8]])

In [80]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])
c = np.append(a, b)
print(c)

[1 2 3 4 5 6 7 8 9]


In [81]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9]])
c = np.append(a, b, axis=0)
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [82]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7], [8]])
c = np.append(a, b, axis=1)
print(c)

[[1 2 3 7]
 [4 5 6 8]]


### 배열 요소 제거 : np.delete()
- 배열 arr의 끝에 obj의 요소를 제거한 결과를 반환함, 배열 arr 자체는 변경되지 않음

In [83]:
a = np.arange(12)
print(a)

#1차원 배열에서 index 5 인 항목 제거
print(np.delete(a, 5))

#1차원 배열에서 index 2, 4, 6인 항목 제거
print(np.delete(a, [2, 4, 6]))

print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11]
[ 0  1  2  3  4  6  7  8  9 10 11]
[ 0  1  3  5  7  8  9 10 11]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [84]:
#0~11 수를 2차원(3, 4)형상으로 만듦
a = np.arange(12).reshape(3, 4)
print(a, '\n')

#축이 지정되지 않으면 1차원으로 변환. 배열에서 index 5인 항목 제거
print(np.delete(a, 5),'\n')

#축을 지정하면, 축을 따라 지정한 index의 sub_array를 제거한 array를 반환
print(np.delete(a, 1, axis=0),'\n')

#축을 지정하면, 축을 따라 지정한 index의 sub_array를 제거한 array 반환
print(np.delete(a, 1, axis=1))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]] 

[ 0  1  2  3  4  6  7  8  9 10 11] 

[[ 0  1  2  3]
 [ 8  9 10 11]] 

[[ 0  2  3]
 [ 4  6  7]
 [ 8 10 11]]


In [85]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(a)
print('-------------')

print(np.delete(a, [1, 3, 5]))
print('-------------')

print(np.delete(a, [0, 1], axis = 0))
print('-------------')

print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
-------------
[ 1  3  5  7  8  9 10 11 12]
-------------
[[ 9 10 11 12]]
-------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


### 배열 요소 삽입 : np.insert()
- 배열 arr의 obj의 요소에 values를 삽입한 결과를 반환함, 배열 arr 자체는 변경되지 않음

In [86]:
a = np.array([[1, 1], [2, 2], [3, 3]])
print(a)
print('-------------')

print(np.insert(a, 1, 5))
print('-------------')

print(np.insert(a, 1, 5, axis=0))
print('-------------')

print(np.insert(a, 1, 5, axis=1))
print('-------------')

print(np.insert(a, 1, [11, 12, 13], axis=1))
print('-------------')

print(a)

[[1 1]
 [2 2]
 [3 3]]
-------------
[1 5 1 2 2 3 3]
-------------
[[1 1]
 [5 5]
 [2 2]
 [3 3]]
-------------
[[1 5 1]
 [2 5 2]
 [3 5 3]]
-------------
[[ 1 11  1]
 [ 2 12  2]
 [ 3 13  3]]
-------------
[[1 1]
 [2 2]
 [3 3]]


### 배열 요소 정렬 : np.sort()
- 배열 arr의 요소들을 오름차순으로 정렬한 결과를 반환
- kind는 정렬 알고리즘 : {‘quicksort’, ‘mergesort’, ‘heapsort’, ‘stable’}, 기본값은 ‘quicksort’
- order는 정렬 기준 : 배열 arr가 필드를 가진 경우, 필드명으로 정렬 기준을 지정

In [87]:
a = np.array([[1, 4], [3, 1]])
print(a)
print('-------------')
print(np.sort(a))
print('-------------')
print(np.sort(a, axis=1))
print('-------------')
print(np.sort(a, axis=None))
print('-------------')
print(np.sort(a, axis=0))

[[1 4]
 [3 1]]
-------------
[[1 4]
 [1 3]]
-------------
[[1 4]
 [1 3]]
-------------
[1 1 3 4]
-------------
[[1 1]
 [3 4]]


In [88]:
dtype = [('name', 'S10'), ('height', float), ('age', int)]
values = [('Arthur', 1.8, 41), ('Lancelot', 1.9, 38),
          ('Galand', 1.7, 38)]
a = np.array(values, dtype=dtype)
print(a, '\n')

print(np.sort(a, order='height'))
print(np.sort(a, order=['age', 'height']))

[(b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38) (b'Galand', 1.7, 38)] 

[(b'Galand', 1.7, 38) (b'Arthur', 1.8, 41) (b'Lancelot', 1.9, 38)]
[(b'Galand', 1.7, 38) (b'Lancelot', 1.9, 38) (b'Arthur', 1.8, 41)]


### 배열 요소 연결 : np.concatenate()

In [89]:
list1 = [1, 2, 3]
list2 = [4, 5, 6]
print(list1 + list2)
print('-------------')
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(arr1 + arr2)

[1, 2, 3, 4, 5, 6]
-------------
[5 7 9]


In [90]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
print(np.concatenate((arr1, arr2)))

[1 2 3 4 5 6]


In [91]:
arr1 = np.array([[1, 2, 3]])
arr2 = np.array([[4, 5, 6]])

print(np.concatenate((arr1, arr2), axis=0))
print('-------------')
print(np.concatenate((arr1, arr2), axis=1))

[[1 2 3]
 [4 5 6]]
-------------
[[1 2 3 4 5 6]]


In [92]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6]])
print(np.concatenate((arr1, arr2), axis=0))
print('-------------')

#두번째 축(axis=1)을 따라 연결하기 위해 transpose를 사용
print(np.concatenate((arr1, arr2.T), axis=1))
print('-------------')

print(np.concatenate((arr1, arr2), axis=None))

[[1 2]
 [3 4]
 [5 6]]
-------------
[[1 2 5]
 [3 4 6]]
-------------
[1 2 3 4 5 6]


### 행렬의 전치 : np.transpose(), np.T

In [93]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [94]:
x = np.arange(4).reshape((2,2))
x

array([[0, 1],
       [2, 3]])

In [95]:
a = np.arange(15).reshape(3, 5)
print(a)
print('-------------')
print(a.T)
print('-------------')
print(np.transpose(a))

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
-------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
-------------
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]


In [96]:
a = np.arange(15).reshape(3, 5)
b = a.T
c = b.shape
print(a)
print(b)
print(c)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
(5, 3)


### reshape() 함수 
- 데이터를 변경하지 않고 배열을 새로운 shape로 변경
    - 매개변수 -1을 입력하면 다차원 배열을 1차원으로 변경하여 반환
    - 매개변수 -1을 행, 열에 입력 가능 (-1 : 알 수 없는 행, 열로 지정)

In [97]:
arr = np.arange(12).reshape(3,4)
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [98]:
print(arr.reshape(-1))
arr1 = arr.reshape(-1)
arr1

[ 0  1  2  3  4  5  6  7  8  9 10 11]


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [99]:
arr.shape

(3, 4)

In [100]:
arr1.shape

(12,)

In [101]:
arr.reshape(-1, 2)

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [102]:
arr.reshape(3, -1)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [103]:
arr = np.arange(24).reshape(2, 3, 4)  #24까지 2개로 나눈다(3행 4열짜리로)
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]],

       [[12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

In [104]:
arr.shape

(2, 3, 4)

In [105]:
arr.ndim

3

In [106]:
arr.size

24

In [107]:
arr.dtype

dtype('int64')

In [109]:
arr = np.array([[[0, 1, 2, 3],
                 [4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15],
                 [16, 17, 18, 19],
                 [20, 21, 22, 23]]])
arr

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15],
        [16, 17, 18, 19],
        [20, 21, 22, 23]]])

- `flatten()`, `ravel()` 함수
    - 다차원 배열을 1차원으로 변경
    - flatten() : 배열을 복사하여 변경
    - ravel() : 배열을 원본 배열과 공유하여 변경

In [110]:
arr = np.arange(12).reshape(3,4)        
print(arr)
print(arr.flatten())        #(얕은복사)
arr1 = arr.flatten()


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [111]:
arr = np.arange(12).reshape(3,4)        
print(arr)
print(arr.flatten())        #(얕은복사)
arr1 = arr.reshape(-1)      #(flatten과 동일)


[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


In [112]:
arr = np.arange(12).reshape(3,4)
print(arr)
print(arr.ravel())          #(깊은복사)
arr1 = arr.ravel()

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]


- `flatten()` 
    - 여러 행렬의 함수를 하나의 행 또는 열로 변환
    - 값을 바꾸게 되면 이전 소스 데이터는 변경 안되는 함수 

In [113]:
a = np.arange(24).reshape(6,4)
print(f'flatten()전: a값\n {a}')
b = a.flatten()
b[0] = 100
print(f'flatten()후: a값\n {a}')
print(f'b값\n {b}')

flatten()전: a값
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
flatten()후: a값
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
b값
 [100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]


In [114]:
a = np.arange(24).reshape(6,4)
print(f'flatten()전: a값\n {a}')
b = a.ravel()
b[0] = 100
print(f'flatten()후: a값\n {a}')
print(f'b값\n {b}')

flatten()전: a값
 [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]
flatten()후: a값
 [[100   1   2   3]
 [  4   5   6   7]
 [  8   9  10  11]
 [ 12  13  14  15]
 [ 16  17  18  19]
 [ 20  21  22  23]]
b값
 [100   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23]
