## Numpy_calculation

### 넘파이 배열 연산
- 더하기, 빼기, 곱하기 등이 가능

In [8]:
import numpy as np

In [2]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])
print(arr1 + arr2)
print('---------')
print(arr1 - arr2)
print('---------')
print(arr1 * arr2)
print('---------')
print(arr1 / arr2)


[[ 6  8]
 [10 12]]
---------
[[-4 -4]
 [-4 -4]]
---------
[[ 5 12]
 [21 32]]
---------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [3]:
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

print(np.add(arr1, arr2))
print('----------')
print(np.subtract(arr1, arr2))
print('----------')
print(np.multiply(arr1, arr2))
print('----------')
print(np.divide(arr1, arr2))

[[ 6  8]
 [10 12]]
----------
[[-4 -4]
 [-4 -4]]
----------
[[ 5 12]
 [21 32]]
----------
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
print(A, '\n')
print(B, '\n')
print(A * B, '\n')      # elementwise product
print(A @ B, '\n')      # matrix product
print(A.dot(B), '\n')   # another matrix product

[[1 2]
 [3 4]] 

[[5 6]
 [7 8]] 

[[ 5 12]
 [21 32]] 

[[19 22]
 [43 50]] 

[[19 22]
 [43 50]] 



- 평균, 중앙값, 합, 최대값, 최소값 계산

In [5]:
array_data = np.array([3, 7, 1, 2, 21])
np.mean(array_data)

np.float64(6.8)

In [6]:
np.median(array_data)

np.float64(3.0)

In [7]:
np.max(array_data)

np.int64(21)

In [8]:
np.min(array_data)

np.int64(1)

In [9]:
np.sum(array_data)

np.int64(34)

In [10]:
#행렬의 자리수를 비교하여 큰 값을 반환

arr1 = np.random.randint(0, 255, size = (3, 3)) 
print(arr1)
print('--------------') 
arr2 = np.random.randint(0, 255, size = (3, 3))
print(arr2)
print('--------------')
np.maximum(arr1, arr2)      

[[110  70 132]
 [ 32 175  88]
 [183  98  97]]
--------------
[[234 102 114]
 [156 148  36]
 [228 205 202]]
--------------


array([[234, 102, 132],
       [156, 175,  88],
       [228, 205, 202]])

### 산술 연산과 브로드 캐스팅
- 브로드 캐스팅 (Broadcasting) : 형상이 다른 배열끼리 연산을 수행할 수 있도록 배열의 형상을 동적으로 변환

In [11]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print(a*5)
print(b+5)
print(a+b)
print(a*b)
print(b-a)
print(b/a)

[ 5 10 15]
[ 9 10 11]
[5 7 9]
[ 4 10 18]
[3 3 3]
[4.  2.5 2. ]


- 배열의 크기가 다른 경우의 연산
    - 앞 배열의 크기 2X2에 맞춰서 뒤쪽 배열도 2X2 크기로 확장된 후 연산을 진행함

In [12]:
a = np.array([[1, 2], [3, 4]])
b = np.array([5, 10])
print(a+b)
print(a*b)

[[ 6 12]
 [ 8 14]]
[[ 5 20]
 [15 40]]


- int, float, str, tuple 객체 : immutable 로 값을 바꿀 수 없다.
- list, dict, numpy의 배열 객체 : mutable로 값을 바꿀 수 있다.
- 얕은 복사 (Shallow Copy) : 객체를 복사할 때 주소값만 복사하는 것

In [13]:
#얕은 복사
a = [1, 2, 3]
b = a[:]        #얕은 복사로 인식
b[0] = 10
print(f'a값 : {a}')
print(f'b값 : {b}')

a값 : [1, 2, 3]
b값 : [10, 2, 3]


In [14]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = a[:]
b[0][0] = 10
print(f'a값 : {a}')
print(f'b값 : {b}')

a값 : [[10, 2, 3], [4, 5, 6], [7, 8, 9]]
b값 : [[10, 2, 3], [4, 5, 6], [7, 8, 9]]


### mutable한 객체의 변수 간 대입
- list의 얕은 복사(Shallow Copy)
    - b에 a를 할당하면 값이 할당되는 것이 아니라 같은 메모리 주소를  참조
    - b를 변경하면 같이 a도 바뀜
    - mutable한 다른 객체 또한 똑같은 현상이 나타남

In [15]:
a = [1, 2, 3]
print(f'변경 전 a값: {a}')
b = a  # shallow copy
b[0] = 5
print(f'변경 후 a값: {a}')
print(f'b값: {b}')
print(id(a), id(b))

변경 전 a값: [1, 2, 3]
변경 후 a값: [5, 2, 3]
b값: [5, 2, 3]
4413804864 4413804864


### immutable한 객체의 변수 간 대입
- str 문자열의 얕은 복사
    - list와 똑같이 b를 a에 할당하면 같은 메모리 주소를 참조
    - 하지만 b에 다른 값을 할당하면 재할당이 이루어지며 메모리 주소가 변경됨
    - a와 b는 다른 값을 가짐

In [16]:
a = "abc"
b = a
print(f'a값: {a}, b값: {b}')
print(id(a), id(b))
b = "abcd"
print(f'a값: {a}, b값: {b}')
print(id(a), id(b))

a값: abc, b값: abc
4342503832 4342503832
a값: abc, b값: abcd
4342503832 4414939568


- 얕은 복사(shallow copy)
    - 리스트에서 copy(복사본)는 주소값의 결과를 가진 새로운 객체
    - list 슬라이싱을 통해 새로운 값을 할당
    - 얕게 복사한 결과 리스트가 원래 리스트를 통해서 변경할 경우 변경된 결과가 같은 id가 부여되며,
    - 서로 영향을 받지 않는다

In [17]:
import copy
a = [1, 2, 3]
b = a.copy()
c = list(a)
d = a[:]

a[0] = "shallow copy"

print(id(a), id(b), id(c), id(d))
print(f'a값: {a}, b값: {b}')
print(f'c값: {c}, d값: {d}')

4414735744 4414483968 4414941632 4414327872
a값: ['shallow copy', 2, 3], b값: [1, 2, 3]
c값: [1, 2, 3], d값: [1, 2, 3]


In [18]:
a = [1, 2, 3]
b = a[:]  # 얕은 복사
print(id(a), id(b))
print(f'a값: {a}, b값: {b}')
print(f'a is b: {a is b}')  # 주소값의 결과로 인한 "is" 비교
print(f'a == b: {a == b}')  # 값 자체의 결과로 인한 "==" 비교

b[0] = 5
print(f'a값: {a}, b값: {b}')

4414472896 4414933376
a값: [1, 2, 3], b값: [1, 2, 3]
a is b: False
a == b: True
a값: [1, 2, 3], b값: [5, 2, 3]


- **리스트안에 리스트 mutable 객체에 의해 mutable 객체에 접근할 경우 문제가 됨**
    - `id(a)` 값과 `id(b)` 값은 다르지만, 그 내부의 객체 `id(a[0])`과 `id(b[0])`은 같은 주소 값을 가짐

In [19]:
a = [[1, 2], [3, 4]]
b = a[:]
print(id(a), id(b))
print(f'a값: {a}, b값: {b}')
print(id(a[0]), id(b[0]))
print(f'a[0]값: {a[0]}, b[0]값: {b[0]}')

a[0][0] = 8
print(f'a값: {a}, b값: {b}')

4414483968 4414937280
a값: [[1, 2], [3, 4]], b값: [[1, 2], [3, 4]]
4414937792 4414937792
a[0]값: [1, 2], b[0]값: [1, 2]
a값: [[8, 2], [3, 4]], b값: [[8, 2], [3, 4]]


In [20]:
a = [[1, 2], [3, 4]]
b = a[:]
print(id(a), id(b))
print(f'a값: {a}, b값: {b}')
print(id(a[0]), id(b[0]))
print(f'a[0]값: {a[0]}, b[0]값: {b[0]}')

a[0] = [8, 9]
print(f'a값: {a}, b값: {b}')

4414838464 4414449216
a값: [[1, 2], [3, 4]], b값: [[1, 2], [3, 4]]
4414686976 4414686976
a[0]값: [1, 2], b[0]값: [1, 2]
a값: [[8, 9], [3, 4]], b값: [[1, 2], [3, 4]]


- 재할당하는 경우 문제가 없음, 메모리 주소도 변경됨

In [9]:
a = [[1, 2], [3, 4]]
b = a[:]
a[0] = [8, 9]
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4389704832 4390794432
a:[[8, 9], [3, 4]], b:[[1, 2], [3, 4]]


In [10]:
# copy모듈의 copy메소드 또한 얕은 복사임
import copy
a = [[1, 2], [3, 4]]
b = copy.copy(a)
a[1].append(5)
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4389703296 4389704320
a:[[1, 2], [3, 4, 5]], b:[[1, 2], [3, 4, 5]]


In [11]:
a = [[1, 2], [3, 4]]
b = a[:]
a[1].append(5)
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4388356288 4390794432
a:[[1, 2], [3, 4, 5]], b:[[1, 2], [3, 4, 5]]


In [12]:
a = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
b = a[:]  # 얕은 복사 / 리스트
b[0][0] = 10
print(f'a:{a}')
print(f'b:{b}')

a:[[10, 2, 3], [4, 5, 6], [7, 8, 9]]
b:[[10, 2, 3], [4, 5, 6], [7, 8, 9]]


- 리스트 값이 모두 불변이면 copy() 메서드는 제대로 동작
- 리스트, 튜플, 딕셔너리 같은 가변(mutable) 객체는 참조일 뿐이다
- 원본과 복사본의 변경사항을 반영함

In [13]:
a = [1, 2, [8, 9]]
b = a.copy()
c = list(a)
d = a[:]
print(id(a), id(b), id(c), id(d))
print(f'a:{a}, b:{b}')
print(f'c:{c}, d:{d}')

4389702848 4389703360 4379774272 4389704320
a:[1, 2, [8, 9]], b:[1, 2, [8, 9]]
c:[1, 2, [8, 9]], d:[1, 2, [8, 9]]


In [14]:
# a[2]의 값이 리스트
# 항목을 변경하면 얕은 복사는 모두 반영된다
a[2][1] = 10
print(id(a), id(b), id(c), id(d))
print(f'a:{a}, b:{b}')
print(f'c:{c}, d:{d}')

4389702848 4389703360 4379774272 4389704320
a:[1, 2, [8, 10]], b:[1, 2, [8, 10]]
c:[1, 2, [8, 10]], d:[1, 2, [8, 10]]


In [15]:
a = [[1, 2], [3, 4]]
b = a[:]
print(id(a), id(b))
print(f'a:{a}, b:{b}')
print(id(a[0]), id(b[0]))
a[0] = [8, 9]
print(f'a[0]:{a[0]}, b[0]:{b[0]}')

4390798720 4391409024
a:[[1, 2], [3, 4]], b:[[1, 2], [3, 4]]
4390796096 4390796096
a[0]:[8, 9], b[0]:[1, 2]


In [17]:
a = [1, 2, [8, 9]]
b = a.copy()
print(id(a), id(b))
print(f'a:{a}, b:{b}')
print(f'a[0]={a[0]}\na[1]={a[1]}\na[2]={a[2]}')
print(f'a[2][0]={a[2][0]}\na[2][1]={a[2][1]}')

4400262848 4400413888
a:[1, 2, [8, 9]], b:[1, 2, [8, 9]]
a[0]=1
a[1]=2
a[2]=[8, 9]
a[2][0]=8
a[2][1]=9


In [18]:
a[0] = 'a'; a[1] = 11; a[2][0] = 'b'; a[2][1] = 22
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4400262848 4400413888
a:['a', 11, ['b', 22]], b:[1, 2, ['b', 22]]


- 깊은 복사(deep copy)

In [19]:
# deepcopy
import copy
import numpy as np
a = [1, 2, [8, 9]]
b = copy.deepcopy(a)
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4400537152 4400719104
a:[1, 2, [8, 9]], b:[1, 2, [8, 9]]


In [20]:
# deepcopy: 변경이 반영되지 않는다
a[2][1] = 10
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4400537152 4400719104
a:[1, 2, [8, 10]], b:[1, 2, [8, 9]]


In [21]:
# deepcopy: 변경이 반영되지 않는다
a[0] = 'a'; a[1] = 11; a[2][0] = 'b'; a[2][1] = 22
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4400537152 4400719104
a:['a', 11, ['b', 22]], b:[1, 2, [8, 9]]


- 깊은 복사는 내부에 객체들까지 모두 새롭게 copy되는 것
- copy.deepcopy 메서드가 해결

In [22]:
a = [[1,2],[3,4]]
b = copy.deepcopy(a)
a[1].append(5)
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4400355392 4391598144
a:[[1, 2], [3, 4, 5]], b:[[1, 2], [3, 4]]


- 배열 복사 : np.copy(arr)
    - array를 복사해서 반환

In [23]:
a = np.array([1, 2, 3])
b = np.copy(a)
a[0] = 3
print(id(a), id(b))
print(f'a:{a}, b:{b}')

4391298288 4391633712
a:[3 2 3], b:[1 2 3]


In [24]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.copy(a)
a[0] = 3
print(id(a), id(b))
print(f'a:{a}')
print(f'b:{b}')

4391634288 4391298288
a:[[3 3 3]
 [4 5 6]
 [7 8 9]]
b:[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [25]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.copy(a)
a[0][1] = 12
print(id(a), id(b))
print(f'a:{a}')
print(f'b:{b}')

4391633328 4391634288
a:[[ 1 12  3]
 [ 4  5  6]
 [ 7  8  9]]
b:[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [26]:
arr = np.arange(10)
print(f'arr : {arr}')
print('---------------')
arr[0] = 100
print(f'arr[0] = 100 --> {arr}')
print('---------------')
arr2 = arr[3:7].copy()
print(f'arr2 = arr[3:7].copy() --> {arr2}')
print('---------------')
arr2[:] = 70
print(f'arr : {arr}')
print(f'arr2[:] = 70 --> {arr2}')

arr : [0 1 2 3 4 5 6 7 8 9]
---------------
arr[0] = 100 --> [100   1   2   3   4   5   6   7   8   9]
---------------
arr2 = arr[3:7].copy() --> [3 4 5 6]
---------------
arr : [100   1   2   3   4   5   6   7   8   9]
arr2[:] = 70 --> [70 70 70 70]


### dtype, type() 차이
- numpy | np.array.dtype
    - dtype는 numpy 배열의 요소 데이터 타입을 반환하는 numpy 배열의 속성
- python | type()
    - type는 지정된 객체의 유형을 반환하는 내장 python 함수

In [27]:
aa = np.arange(6).reshape(2, 3)
print(f'aa\n{aa}')
print(f'aa.dtype --> {aa.dtype}')
print(f'type(aa) --> {type(aa)}')



aa
[[0 1 2]
 [3 4 5]]
aa.dtype --> int64
type(aa) --> <class 'numpy.ndarray'>


In [28]:
# numpy 숫자형이 취할 수 있는 범위 (최소값, 최대값) 확인
print(np.iinfo('int16'))
print(np.iinfo('i4'))
print(np.iinfo(int))
print(np.iinfo('uint64'))

Machine parameters for int16
---------------------------------------------------------------
min = -32768
max = 32767
---------------------------------------------------------------

Machine parameters for int32
---------------------------------------------------------------
min = -2147483648
max = 2147483647
---------------------------------------------------------------

Machine parameters for int64
---------------------------------------------------------------
min = -9223372036854775808
max = 9223372036854775807
---------------------------------------------------------------

Machine parameters for uint64
---------------------------------------------------------------
min = 0
max = 18446744073709551615
---------------------------------------------------------------



### 배열 데이터의 파일 입출력
- 저장 및 로딩
    - np.save() -> np.load() : 객체를 저장, 로딩
        - np형식으로 저장
        - 저장할 때와 동일한 형식으로 로딩됨
    - np.savetxt() -> np.loadtxt()  : 파일로 저장, 로딩
        - 텍스트 형식으로 저장
        - 저장할 떄의 데이터 형식을 유지하지 못함

In [29]:
arr = np.arange(10)
print(arr)
np.save('some_array', arr)
np.load('some_array.npy')

[0 1 2 3 4 5 6 7 8 9]


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [30]:
arr1 = np.arange(10)
print(arr1)
np.savetxt('some_array1', arr1)
np.loadtxt('some_array1')

[0 1 2 3 4 5 6 7 8 9]


array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])