## Numpy_indexing and slicing
- numpy 배열의  인덱싱과 슬라이싱은 파이썬 리스트의 인덱싱, 슬라이싱과 동일
    - 인덱싱 : 값, 슬라이싱 : 배열

In [1]:
import numpy as np

### 1차원 배열 인덱싱과 슬라이싱 방법

In [3]:
arr1 = np.arange(10)
print(arr1,'\n')
print(arr1[1])
print(arr1[:6])
print(arr1[0:5],'\n')
print(arr1[::2])
print(arr1[1::2])
print(arr1[1:7:2],'\n')
print(arr1[-3:9])
print(arr1[:-3])
print(arr1[-3:2:-1],'\n')
print(arr1[5:2])
print(arr1[5:])
print(arr1[1:])

[0 1 2 3 4 5 6 7 8 9] 

1
[0 1 2 3 4 5]
[0 1 2 3 4] 

[0 2 4 6 8]
[1 3 5 7 9]
[1 3 5] 

[7 8]
[0 1 2 3 4 5 6]
[7 6 5 4 3] 

[]
[5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


- 부분집합의 값이 변경되면 원래 배열의 값도 변경
    - 배열의 부분 집합을 추출했을 때 부분 집합에 새로운 값이 복사되는 것이 아니라, 부분 집합이 원래 배열과 메모리를 공유함

In [4]:
arr = np.arange(10)
print(arr)
arr[0] = 100
print(arr)
print('-----------')
arr1 = arr[3:7]
print(arr1)
print('-----------')
arr1[:] = 90
print(arr1)
print(arr)

[0 1 2 3 4 5 6 7 8 9]
[100   1   2   3   4   5   6   7   8   9]
-----------
[3 4 5 6]
-----------
[90 90 90 90]
[100   1   2  90  90  90  90   7   8   9]


### 2차원 배열 인덱싱과 슬라이싱 방법

In [5]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2, '\n')
print(arr2[2, 1])
print(arr2[:2, :2])
print(arr2[:, ::-1], '\n')
print(arr2[:, :])
print(arr2[1, :])
print(arr2[1, 2])

[[0 1 2]
 [3 4 5]
 [6 7 8]] 

7
[[0 1]
 [3 4]]
[[2 1 0]
 [5 4 3]
 [8 7 6]] 

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[3 4 5]
5


In [6]:
arr2 = np.arange(9).reshape(3, 3)
print(arr2)
print('-----------')
print(arr2[0:2, 0:2])


[[0 1 2]
 [3 4 5]
 [6 7 8]]
-----------
[[0 1]
 [3 4]]


In [10]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]])

rows = np.array([[0, 0], [3, 0]], dtype=int)
columns = np.array([[0, 2], [2, 1]], dtype=int)

print(f'arr[rows, columns]\n{arr[rows, columns]}')
print(arr[rows, columns].shape)

arr[rows, columns]
[[ 0  2]
 [11  1]]
(2, 2)


In [11]:
arr = np.array([[0, 1, 2],
                [3, 4, 5],
                [6, 7, 8],
                [9, 10, 11]])

rows = np.array([[0, 0], [3, 0]], dtype=np.intp)
columns = np.array([[0, 2], [2, 1]], dtype=np.intp)

print(f'arr[rows, columns]\n{arr[rows, columns]}')
print(arr[rows, columns].shape)

arr[rows, columns]
[[ 0  2]
 [11  1]]
(2, 2)


In [7]:
arr=np.arange(16).reshape(4,4)
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [8]:
arr[[1, 3], :]      #1행과 3행을 추출

array([[ 4,  5,  6,  7],
       [12, 13, 14, 15]])

In [9]:
arr[[1, 3], [1, 3]]     #1행1열과 3행3열을 추출

array([ 5, 15])

### 3차원 배열 인덱싱과 슬라이싱 방법

In [12]:
arr3 = np.reshape(np.arange(24), (2, 3, 4))
print(arr3, '\n')
print(arr3[1,1,2])
print(arr3[1][2][3])
print(arr3[0, :, 1], '\n')
print(arr3[1, :, :], '\n')
print(arr3[:2, 1, :2])

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]] 

18
23
[1 5 9] 

[[12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]] 

[[ 4  5]
 [16 17]]


- ndarray 객체 사용을 위한 메소드

    | 메소드 | 설명 |
    | :---: | :---: |
    | sum() | 배열 원소들의 합 |
    | mean() | 배열 원소들의 평균 |
    | max() | 배열 원소들 중 최대값 |
    | min() | 배열 원소들 중 최소값 |
    | argmax() | 배열 원소들 중 최대값의 인덱스 |
    | argmin() | 배열 원소들 중 최소값의 인덱스 |
    | where() | 조건에 따라 선별적으로 값을 선택 |
    | sort() | 배열을 정렬 |

### 논리적 인덱싱

In [13]:
ages = np.array([18, 19, 25, 30, 28])
y = ages > 20
print(y)
print(ages[ages > 20])

[False False  True  True  True]
[25 30 28]


In [14]:
np_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np_array > 5      #상수를 가지고 비교 연산자를 사용하면 배열의 크기에 맞춰서 True, False로 반환

array([[False, False, False],
       [False, False,  True],
       [ True,  True,  True]])

In [15]:
np_array[np_array > 5]

array([6, 7, 8, 9])

In [16]:
np_array[(np_array > 3) & (np_array < 8)]

array([4, 5, 6, 7])

In [17]:
np_array[:, 2] > 5

array([False,  True,  True])

In [18]:
np_array[:, 2]

array([3, 6, 9])

- 배열에서 특정 조건을 만족하는 행만 추출

In [19]:
players = [[170, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]
np_players = np.array(players)

print('몸무게가 80 이상인 선수 정보');
print(np_players[np_players[:, 1]>=80.0])

print('키가 175 이상인 선수 정보');
print(np_players[np_players[:, 0] >= 175.0])

몸무게가 80 이상인 선수 정보
[[183.   86.2]
 [176.   80.1]]
키가 175 이상인 선수 정보
[[183.   86.2]
 [181.   78.5]
 [176.   80.1]]


In [20]:
players = [[170, 76.4],
           [183, 86.2],
           [181, 78.5],
           [176, 80.1]]
np_players = np.array(players)
print(np_players[(np_players[:, 0] >= 180.0) & (np_players[:, 1] >= 80.0)])

[[183.   86.2]]


In [21]:
x = np.array([[1.83, 1.76, 1.69, 1.86, 1.77, 1.73],
              [86.0, 74.0, 59.0, 95.0, 80.0, 68.0]])
y = x[0:2, 1:3]
z1 = x[0][1]
z2 = x[0:]

print(y)
print(z1)
print(z2)
print('-------')

print('x shape :', x.shape)
print('y shape :', y.shape)
print('z1 shape :', z1.shape)
print('z2 shape :', z2.shape)

bmi = x[0] / (x[1]**2)
print('BMI data')
print(bmi)

[[ 1.76  1.69]
 [74.   59.  ]]
1.76
[[ 1.83  1.76  1.69  1.86  1.77  1.73]
 [86.   74.   59.   95.   80.   68.  ]]
-------
x shape : (2, 6)
y shape : (2, 2)
z1 shape : ()
z2 shape : (2, 6)
BMI data
[0.00024743 0.0003214  0.00048549 0.00020609 0.00027656 0.00037413]
